/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import ALexico.AnalizadorLexico;
import ALexico.Token;
import ASintactico.AnalizadorSintactico;
import ASintactico.Transiciones;
import Reportes.FuncionesYSusParametros;
import Reportes.ReporteCantidadLLamadasFunctions;
import Reportes.ReporteTablaDeSimbolos;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenny
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    numeroLinea numeroLinea;
    AnalizadorSintactico aS = new AnalizadorSintactico();

    public Vista() {
        initComponents();
        numeroLinea = new numeroLinea(entrada1);
        jScrollPane8.setRowHeaderView(numeroLinea);
        this.filtroTablaGlobal.addItem("Simbolo");
        this.filtroTablaGlobal.addItem("Tipo");
        this.filtroTablaGlobal1.addItem("Simbolo");
        this.filtroTablaGlobal1.addItem("Tipo");
        this.filtroTablaGlobal2.addItem("Simbolo");
        this.filtroTablaGlobal2.addItem("Tipo");
        this.filtroTablaGlobal3.addItem("Simbolo");
        this.filtroTablaGlobal4.addItem("Simbolo");
        this.filtroTablaGlobal5.addItem("Nombre Funcion");
        this.filtroTablaGlobal5.addItem("Cantidad Funciones");
        this.filtroTablaGlobal6.addItem("Nombre Funcion");
        this.filtroTablaGlobal6.addItem("Parametros");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CargarDatos1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        entrada1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonAnalizarEntrada = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaSimbolos = new javax.swing.JTable();
        JTXBuscarTS = new javax.swing.JTextField();
        filtroTablaGlobal = new javax.swing.JComboBox<>();
        jDesktopPane10 = new javax.swing.JDesktopPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        TSXBloqueCodigo = new javax.swing.JTable();
        filtroTablaGlobal1 = new javax.swing.JComboBox<>();
        JTXBuscarTS1 = new javax.swing.JTextField();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jDesktopPane13 = new javax.swing.JDesktopPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        cantidadLlamadasAFuncionTable = new javax.swing.JTable();
        filtroTablaGlobal5 = new javax.swing.JComboBox<>();
        JTXBuscarTS5 = new javax.swing.JTextField();
        jDesktopPane14 = new javax.swing.JDesktopPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        parametrosFunciones = new javax.swing.JTable();
        filtroTablaGlobal6 = new javax.swing.JComboBox<>();
        JTXBuscarTS6 = new javax.swing.JTextField();
        jDesktopPane12 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCantidadFOM = new javax.swing.JTable();
        cantidadFOMLabel = new javax.swing.JLabel();
        filtroTablaGlobal2 = new javax.swing.JComboBox<>();
        JTXBuscarTS2 = new javax.swing.JTextField();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jDesktopPane15 = new javax.swing.JDesktopPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaDeEL = new javax.swing.JTable();
        JTXBuscarTS3 = new javax.swing.JTextField();
        filtroTablaGlobal3 = new javax.swing.JComboBox<>();
        jDesktopPane16 = new javax.swing.JDesktopPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaDeES = new javax.swing.JTable();
        filtroTablaGlobal4 = new javax.swing.JComboBox<>();
        JTXBuscarTS4 = new javax.swing.JTextField();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CARGAR ARCHIVO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("ENTRADA DEL TEXTO");

        CargarDatos1.setBackground(new java.awt.Color(255, 255, 255));
        CargarDatos1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        CargarDatos1.setForeground(new java.awt.Color(0, 204, 0));
        CargarDatos1.setText("CARGAR DATOS");
        CargarDatos1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CargarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDatos1ActionPerformed(evt);
            }
        });

        jScrollPane8.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane8.setForeground(new java.awt.Color(102, 255, 255));

        entrada1.setBackground(new java.awt.Color(51, 51, 51));
        entrada1.setColumns(20);
        entrada1.setForeground(new java.awt.Color(102, 255, 255));
        entrada1.setRows(5);
        entrada1.setCaretColor(new java.awt.Color(255, 255, 255));
        entrada1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        entrada1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane8.setViewportView(entrada1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(322, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(CargarDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane8)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarDatos1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANALIZADOR SINTACTICO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 102, 0));

        salida.setBackground(new java.awt.Color(51, 51, 51));
        salida.setColumns(20);
        salida.setForeground(new java.awt.Color(0, 204, 0));
        salida.setRows(5);
        salida.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jScrollPane3.setViewportView(salida);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("SALIDA DEL TEXTO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        botonAnalizarEntrada.setBackground(new java.awt.Color(255, 255, 255));
        botonAnalizarEntrada.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        botonAnalizarEntrada.setForeground(new java.awt.Color(0, 204, 0));
        botonAnalizarEntrada.setText("ANALIZAR ENTRADA");
        botonAnalizarEntrada.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botonAnalizarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botonAnalizarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAnalizarEntrada)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(358, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("INICIO", jDesktopPane1);

        tablaSimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Símbolo", "Tipo", "Valor", "Línea", "Columna"
            }
        ));
        jScrollPane4.setViewportView(tablaSimbolos);

        JTXBuscarTS.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTXBuscarTSCaretUpdate(evt);
            }
        });

        jDesktopPane9.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(JTXBuscarTS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(filtroTablaGlobal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane9Layout = new javax.swing.GroupLayout(jDesktopPane9);
        jDesktopPane9.setLayout(jDesktopPane9Layout);
        jDesktopPane9Layout.setHorizontalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtroTablaGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTXBuscarTS, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane9Layout.setVerticalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filtroTablaGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTXBuscarTS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Globales", jDesktopPane9);

        TSXBloqueCodigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Símbolo", "Tipo", "Valor", "Línea", "Columna"
            }
        ));
        jScrollPane5.setViewportView(TSXBloqueCodigo);

        JTXBuscarTS1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTXBuscarTS1CaretUpdate(evt);
            }
        });

        jDesktopPane10.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane10.setLayer(filtroTablaGlobal1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane10.setLayer(JTXBuscarTS1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane10Layout = new javax.swing.GroupLayout(jDesktopPane10);
        jDesktopPane10.setLayout(jDesktopPane10Layout);
        jDesktopPane10Layout.setHorizontalGroup(
            jDesktopPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtroTablaGlobal1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTXBuscarTS1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane10Layout.setVerticalGroup(
            jDesktopPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane10Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jDesktopPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filtroTablaGlobal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTXBuscarTS1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Por bloque de código", jDesktopPane10);

        jDesktopPane4.setLayer(jTabbedPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Tabla de Símbolos", jDesktopPane4);

        cantidadLlamadasAFuncionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Funcion", "Cantidad Veces Llamadas"
            }
        ));
        jScrollPane9.setViewportView(cantidadLlamadasAFuncionTable);

        JTXBuscarTS5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTXBuscarTS5CaretUpdate(evt);
            }
        });

        jDesktopPane13.setLayer(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane13.setLayer(filtroTablaGlobal5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane13.setLayer(JTXBuscarTS5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane13Layout = new javax.swing.GroupLayout(jDesktopPane13);
        jDesktopPane13.setLayout(jDesktopPane13Layout);
        jDesktopPane13Layout.setHorizontalGroup(
            jDesktopPane13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtroTablaGlobal5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTXBuscarTS5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane13Layout.setVerticalGroup(
            jDesktopPane13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jDesktopPane13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTXBuscarTS5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTablaGlobal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Cantidad de veces que se llama a una Función", jDesktopPane13);

        parametrosFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Funcion", "Parametros"
            }
        ));
        jScrollPane10.setViewportView(parametrosFunciones);

        JTXBuscarTS6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTXBuscarTS6CaretUpdate(evt);
            }
        });

        jDesktopPane14.setLayer(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane14.setLayer(filtroTablaGlobal6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane14.setLayer(JTXBuscarTS6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane14Layout = new javax.swing.GroupLayout(jDesktopPane14);
        jDesktopPane14.setLayout(jDesktopPane14Layout);
        jDesktopPane14Layout.setHorizontalGroup(
            jDesktopPane14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane14Layout.createSequentialGroup()
                .addGroup(jDesktopPane14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filtroTablaGlobal6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTXBuscarTS6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane14Layout.setVerticalGroup(
            jDesktopPane14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane14Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jDesktopPane14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTXBuscarTS6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTablaGlobal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Parametros de una Función ", jDesktopPane14);

        tablaCantidadFOM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Simbolo", "Tipo", "Valor", "Linea", "Columna"
            }
        ));
        jScrollPane2.setViewportView(tablaCantidadFOM);

        cantidadFOMLabel.setText("jLabel1");

        JTXBuscarTS2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTXBuscarTS2CaretUpdate(evt);
            }
        });

        jDesktopPane12.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane12.setLayer(cantidadFOMLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane12.setLayer(filtroTablaGlobal2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane12.setLayer(JTXBuscarTS2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane12Layout = new javax.swing.GroupLayout(jDesktopPane12);
        jDesktopPane12.setLayout(jDesktopPane12Layout);
        jDesktopPane12Layout.setHorizontalGroup(
            jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane12Layout.createSequentialGroup()
                        .addComponent(cantidadFOMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filtroTablaGlobal2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTXBuscarTS2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jDesktopPane12Layout.setVerticalGroup(
            jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane12Layout.createSequentialGroup()
                .addGroup(jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane12Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cantidadFOMLabel)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(filtroTablaGlobal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTXBuscarTS2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Cantidad de Funciones o Métodos", jDesktopPane12);

        jDesktopPane5.setLayer(jTabbedPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Funciones o Métodos", jDesktopPane5);

        tablaDeEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "TOKEN", "LÍNEA", "COLUMNA"
            }
        ));
        jScrollPane6.setViewportView(tablaDeEL);

        JTXBuscarTS3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTXBuscarTS3CaretUpdate(evt);
            }
        });

        jDesktopPane15.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane15.setLayer(JTXBuscarTS3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane15.setLayer(filtroTablaGlobal3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane15Layout = new javax.swing.GroupLayout(jDesktopPane15);
        jDesktopPane15.setLayout(jDesktopPane15Layout);
        jDesktopPane15Layout.setHorizontalGroup(
            jDesktopPane15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane15Layout.createSequentialGroup()
                .addGroup(jDesktopPane15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDesktopPane15Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filtroTablaGlobal3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTXBuscarTS3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jDesktopPane15Layout.setVerticalGroup(
            jDesktopPane15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTXBuscarTS3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTablaGlobal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Léxicos", jDesktopPane15);

        tablaDeES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "TOKEN", "LÍNEA", "COLUMNA"
            }
        ));
        jScrollPane7.setViewportView(tablaDeES);

        JTXBuscarTS4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                JTXBuscarTS4CaretUpdate(evt);
            }
        });

        jDesktopPane16.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane16.setLayer(filtroTablaGlobal4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane16.setLayer(JTXBuscarTS4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane16Layout = new javax.swing.GroupLayout(jDesktopPane16);
        jDesktopPane16.setLayout(jDesktopPane16Layout);
        jDesktopPane16Layout.setHorizontalGroup(
            jDesktopPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane16Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jDesktopPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane16Layout.createSequentialGroup()
                        .addComponent(filtroTablaGlobal4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTXBuscarTS4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jDesktopPane16Layout.setVerticalGroup(
            jDesktopPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTXBuscarTS4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTablaGlobal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane5.addTab("Sintácticos", jDesktopPane16);

        jDesktopPane6.setLayer(jTabbedPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Errores", jDesktopPane6);

        jDesktopPane2.setLayer(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REPORTES", jDesktopPane2);

        tablaEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ESTADO ACTUAL", "TOKEN", "SIGUIENTE ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tablaEstados);

        jDesktopPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 197, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TRANSICIONES", jDesktopPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDatos1ActionPerformed
        abrirFileChooser();
    }//GEN-LAST:event_CargarDatos1ActionPerformed

    private void botonAnalizarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarEntradaActionPerformed
        salida.setText("");
        AnalizadorLexico al = new AnalizadorLexico(entrada1.getText());
        ArrayList<Token> tokens = al.analizarCodigoFuente();
        aS = new AnalizadorSintactico();
        salida.setText(aS.analizarSintatico(tokens));
        llenarTablaErroresLexicos_Sintacticos(aS.EtokensLexicos, this.tablaDeEL);
        llenarTablaErroresLexicos_Sintacticos(aS.EtokensSintacticos, this.tablaDeES);
        /*for (String error : aS.erroresSintacticos) {
        salida.setText(salida.getText() + "\n" + error);
        }*/
        for (int i = 0; i < 1; i++) {
            try {
                salida.setText(salida.getText() + "\n" + aS.erroresSintacticos.get(0));
            } catch (IndexOutOfBoundsException e) {
            }
        }
        for (String error : aS.erroresLexicos) {
            salida.setText(salida.getText() + "\n" + error);
        }
        if (aS.erroresLexicos.size() == 0) {
            salida.setText(salida.getText() + "\nAnalisis Lexico correctamente");
        }
        this.tablaEstados.setModel(aS.tabla1);
        if (aS.erroresSintacticos.size() == 0) {
            LlenarTablaSimbolos(aS.listaRepTS, this.tablaSimbolos);
            LlenarTablaSimbolos(aS.listaRepTSXBloqueCodigo, this.TSXBloqueCodigo);
            LlenarTablaSimbolos(aS.cantidadFuncionesOMetodos, this.tablaCantidadFOM);
            darValorALabelCantidadFOM("Cantidad de funciones: " + aS.cantidadFuncionesOMetodos.size());
            llenarTablaCantidadVecesLlamadaAFuncion(aS.funcionesLLamadasCantidad, this.cantidadLlamadasAFuncionTable);
            llenarTablaParametrosFunciones(aS.funcionesYsusParametros, this.parametrosFunciones);
        } else {
            Clear_Table1(this.tablaSimbolos);
            Clear_Table1(this.TSXBloqueCodigo);
            Clear_Table1(this.tablaCantidadFOM);
            Clear_Table1(this.cantidadLlamadasAFuncionTable);
            Clear_Table1(this.parametrosFunciones);
            darValorALabelCantidadFOM(" ");
        }
    }//GEN-LAST:event_botonAnalizarEntradaActionPerformed

    private void JTXBuscarTSCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTXBuscarTSCaretUpdate
        // TODO add your handling code here:
        buscarenTablaSimbolos();

    }//GEN-LAST:event_JTXBuscarTSCaretUpdate

    private void JTXBuscarTS1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTXBuscarTS1CaretUpdate
        // TODO add your handling code here:
        buscarenTablaSimbolosXBloqueCodigo();
    }//GEN-LAST:event_JTXBuscarTS1CaretUpdate

    private void JTXBuscarTS2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTXBuscarTS2CaretUpdate
        // TODO add your handling code here:
        buscarenCantidadDeFunciones();
    }//GEN-LAST:event_JTXBuscarTS2CaretUpdate

    private void JTXBuscarTS3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTXBuscarTS3CaretUpdate
        // TODO add your handling code here:
        buscarEnTablaErroresLexicos();
    }//GEN-LAST:event_JTXBuscarTS3CaretUpdate

    private void JTXBuscarTS4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTXBuscarTS4CaretUpdate
        // TODO add your handling code here:
        buscarEnTablaErroresSintacticos();
    }//GEN-LAST:event_JTXBuscarTS4CaretUpdate

    private void JTXBuscarTS5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTXBuscarTS5CaretUpdate
        // TODO add your handling code here:
        buscarenTablaCantidadDeVecesFuncion();
    }//GEN-LAST:event_JTXBuscarTS5CaretUpdate

    private void JTXBuscarTS6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_JTXBuscarTS6CaretUpdate
        // TODO add your handling code here:
        buscarenTablaParametrosFuncion();
    }//GEN-LAST:event_JTXBuscarTS6CaretUpdate

    public void buscarenTablaSimbolos() {
        if (this.JTXBuscarTS.getText().equalsIgnoreCase("")) {
            LlenarTablaSimbolos(aS.listaRepTS, this.tablaSimbolos);
        } else {
            int num = this.filtroTablaGlobal.getSelectedIndex();
            ArrayList<ReporteTablaDeSimbolos> rn = new ArrayList<>();
            for (ReporteTablaDeSimbolos rts : aS.listaRepTS) {
                if (num == 0) {
                    if (rts.getSimbolo().contains(this.JTXBuscarTS.getText())) {
                        rn.add(rts);
                    }
                } else if (num == 1) {
                    if (rts.getTipo().contains(this.JTXBuscarTS.getText())) {
                        rn.add(rts);
                    }
                }
            }
            LlenarTablaSimbolos(rn, this.tablaSimbolos);
        }
    }

    public void buscarenTablaSimbolosXBloqueCodigo() {
        if (this.JTXBuscarTS1.getText().equalsIgnoreCase("")) {
            LlenarTablaSimbolos(aS.listaRepTSXBloqueCodigo, this.TSXBloqueCodigo);
        } else {
            int num = this.filtroTablaGlobal1.getSelectedIndex();
            ArrayList<ReporteTablaDeSimbolos> rn = new ArrayList<>();
            for (ReporteTablaDeSimbolos rts : aS.listaRepTSXBloqueCodigo) {
                if (num == 0) {
                    if (rts.getSimbolo().contains(this.JTXBuscarTS1.getText())) {
                        rn.add(rts);
                    }
                } else if (num == 1) {
                    if (rts.getTipo().contains(this.JTXBuscarTS1.getText())) {
                        rn.add(rts);
                    }
                }
            }
            LlenarTablaSimbolos(rn, this.TSXBloqueCodigo);
        }
    }

    public void buscarenCantidadDeFunciones() {
        if (this.JTXBuscarTS2.getText().equalsIgnoreCase("")) {
            LlenarTablaSimbolos(aS.cantidadFuncionesOMetodos, this.tablaCantidadFOM);
        } else {
            int num = this.filtroTablaGlobal2.getSelectedIndex();
            ArrayList<ReporteTablaDeSimbolos> rn = new ArrayList<>();
            for (ReporteTablaDeSimbolos rts : aS.cantidadFuncionesOMetodos) {
                if (num == 0) {
                    if (rts.getSimbolo().contains(this.JTXBuscarTS2.getText())) {
                        rn.add(rts);
                    }
                } else if (num == 1) {
                    if (rts.getTipo().contains(this.JTXBuscarTS2.getText())) {
                        rn.add(rts);
                    }
                }
            }
            LlenarTablaSimbolos(rn, this.tablaCantidadFOM);
        }
    }

    public void buscarEnTablaErroresLexicos() {
        if (this.JTXBuscarTS3.getText().equalsIgnoreCase("")) {
            llenarTablaErroresLexicos_Sintacticos(aS.EtokensLexicos, this.tablaDeEL);
        } else {
            int num = this.filtroTablaGlobal3.getSelectedIndex();
            ArrayList<Token> rn = new ArrayList<>();
            for (Token rts : aS.EtokensLexicos) {
                if (num == 0) {
                    if (rts.getLexema().contains(this.JTXBuscarTS3.getText())) {
                        rn.add(rts);
                    }
                }
            }
            llenarTablaErroresLexicos_Sintacticos(rn, this.tablaDeEL);
        }
    }

    public void buscarEnTablaErroresSintacticos() {
        if (this.JTXBuscarTS4.getText().equalsIgnoreCase("")) {
            llenarTablaErroresLexicos_Sintacticos(aS.EtokensSintacticos, this.tablaDeES);
        } else {
            int num = this.filtroTablaGlobal4.getSelectedIndex();
            ArrayList<Token> rn = new ArrayList<>();
            for (Token rts : aS.EtokensSintacticos) {
                if (num == 0) {
                    if (rts.getLexema().contains(this.JTXBuscarTS4.getText())) {
                        rn.add(rts);
                    }
                }
            }
            llenarTablaErroresLexicos_Sintacticos(rn, this.tablaDeES);
        }
    }

    public void buscarenTablaCantidadDeVecesFuncion() {
        if (this.JTXBuscarTS5.getText().equalsIgnoreCase("")) {
            llenarTablaCantidadVecesLlamadaAFuncion(aS.funcionesLLamadasCantidad, this.cantidadLlamadasAFuncionTable);
        } else {
            int num = this.filtroTablaGlobal5.getSelectedIndex();
            ArrayList<ReporteCantidadLLamadasFunctions> rn = new ArrayList<>();
            for (ReporteCantidadLLamadasFunctions rts : aS.funcionesLLamadasCantidad) {
                if (num == 0) {
                    if (rts.getNombreFuncion().contains(this.JTXBuscarTS5.getText())) {
                        rn.add(rts);
                    }
                } else if (num == 1) {
                    if (String.valueOf(rts.getCantidad()).contains(this.JTXBuscarTS5.getText())) {
                        rn.add(rts);
                    }
                }
            }
            llenarTablaCantidadVecesLlamadaAFuncion(rn, this.cantidadLlamadasAFuncionTable);
        }
    }

    public void buscarenTablaParametrosFuncion() {
        if (this.JTXBuscarTS6.getText().equalsIgnoreCase("")) {
            llenarTablaParametrosFunciones(aS.funcionesYsusParametros, this.parametrosFunciones);
        } else {
            int num = this.filtroTablaGlobal6.getSelectedIndex();
            ArrayList<FuncionesYSusParametros> rn = new ArrayList<>();
            for (FuncionesYSusParametros rts : aS.funcionesYsusParametros) {
                if (num == 0) {
                    if (rts.getNombre().contains(this.JTXBuscarTS6.getText())) {
                        rn.add(rts);
                    }
                } else if (num == 1) {
                    if (rts.getParametros().contains(this.JTXBuscarTS6.getText())) {
                        rn.add(rts);
                    }
                }
            }
            llenarTablaParametrosFunciones(rn, this.parametrosFunciones);
        }
    }

    public void darValorALabelCantidadFOM(String valor) {
        this.cantidadFOMLabel.setText(valor);
    }

    public void abrirFileChooser() {
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();

        if (archivo != null || !archivo.getName().equals("")) {

            leerArchivoDeEntrada(archivo.getAbsolutePath(), entrada1);
        }

    }

    private void Clear_Table1(JTable tabla1) {
        DefaultTableModel diseño = (DefaultTableModel) tabla1.getModel();
        while (diseño.getRowCount() > 0) {
            diseño.removeRow(0);
        }
    }

    public void leerArchivoDeEntrada(String nombre, JTextArea areaEntrada) {
        int contadorLienas = 1;
        String linea = "";
        entrada1.setText("");
        try {
            BufferedReader bufer = new BufferedReader(new FileReader(new File(nombre)));
            while ((linea = bufer.readLine()) != null) {
                contadorLienas++;
                System.out.println(linea + " Linea: " + contadorLienas);
                areaEntrada.setText(areaEntrada.getText() + "\n" + linea);
            }
            bufer.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al intentar cargar el archivo");
        } catch (IOException ex) {

        }
    }
    //LLENAR TABLA 

    public static void llenarTabla(int estadoActual, ArrayList<Token> tokens, int tabla[][]) {
        DefaultTableModel tabla1 = new DefaultTableModel();
        String[] columna = new String[3];
        Transiciones transicion = new Transiciones();

        tabla1.addColumn("ESTADO ACTUAL");
        tabla1.addColumn("TOKEN");
        tabla1.addColumn("SIGUIENTE ESTADO");

        for (Token token : tokens) {
            columna[0] = String.valueOf(estadoActual);
            columna[1] = token.getLexema();
            columna[2] = String.valueOf(tabla[estadoActual][transicion.devolverNumeroPorToken(token)]);

            tabla1.addRow(columna);
        }

        Vista.tablaEstados.setModel(tabla1);

    }

    public void llenarTablaCantidadVecesLlamadaAFuncion(ArrayList<ReporteCantidadLLamadasFunctions> lista, JTable tabla) {

        try {
            DefaultTableModel tabla1 = new DefaultTableModel();
            String[] columna = new String[2];

            tabla1.addColumn("Nombre Funcion");
            tabla1.addColumn("Cantidad Veces Llamadas");

            for (ReporteCantidadLLamadasFunctions rep : lista) {
                columna[0] = rep.getNombreFuncion();
                columna[1] = String.valueOf(rep.getCantidad());

                tabla1.addRow(columna);
            }

            tabla.setModel(tabla1);
        } catch (NullPointerException e) {
        }
    }

    public void llenarTablaParametrosFunciones(ArrayList<FuncionesYSusParametros> lista, JTable tabla) {
        try {
            DefaultTableModel tabla1 = new DefaultTableModel();
            String[] columna = new String[2];

            tabla1.addColumn("Nombre Funcion");
            tabla1.addColumn("Parametros");

            for (FuncionesYSusParametros rep : lista) {
                columna[0] = rep.getNombre();
                columna[1] = rep.getParametros();

                tabla1.addRow(columna);
            }

            tabla.setModel(tabla1);
        } catch (NullPointerException e) {
        }
    }

    public void llenarTablaErroresLexicos_Sintacticos(ArrayList<Token> tokens, JTable tablaE) {

        try {
            DefaultTableModel tabla1 = new DefaultTableModel();
            String[] columna = new String[3];
            Transiciones transicion = new Transiciones();

            tabla1.addColumn("TOKEN");
            tabla1.addColumn("LINEA");
            tabla1.addColumn("COLUMNA");

            for (Token token : tokens) {
                columna[0] = token.getLexema();
                columna[1] = String.valueOf(token.getLinea());
                columna[2] = String.valueOf(token.getColumna());

                tabla1.addRow(columna);
            }

            tablaE.setModel(tabla1);
        } catch (NullPointerException e) {
        }

    }

    public void LlenarTablaSimbolos(ArrayList<ReporteTablaDeSimbolos> reportesTS, JTable tabla) {
        try {
            DefaultTableModel tabla1 = new DefaultTableModel();
            String[] columna = new String[5];

            tabla1.addColumn("Simbolo");
            tabla1.addColumn("Tipo");
            tabla1.addColumn("Valor");
            tabla1.addColumn("Linea");
            tabla1.addColumn("Columna");

            for (ReporteTablaDeSimbolos rep : reportesTS) {
                columna[0] = rep.getSimbolo();
                columna[1] = rep.getTipo();
                columna[2] = rep.getValor();
                columna[3] = String.valueOf(rep.getLinea());
                columna[4] = String.valueOf(rep.getColumna());
                tabla1.addRow(columna);
            }
            tabla.setModel(tabla1);
        } catch (Exception e) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarDatos1;
    private javax.swing.JTextField JTXBuscarTS;
    private javax.swing.JTextField JTXBuscarTS1;
    private javax.swing.JTextField JTXBuscarTS2;
    private javax.swing.JTextField JTXBuscarTS3;
    private javax.swing.JTextField JTXBuscarTS4;
    private javax.swing.JTextField JTXBuscarTS5;
    private javax.swing.JTextField JTXBuscarTS6;
    private javax.swing.JTable TSXBloqueCodigo;
    private javax.swing.JButton botonAnalizarEntrada;
    private javax.swing.JLabel cantidadFOMLabel;
    private javax.swing.JTable cantidadLlamadasAFuncionTable;
    private javax.swing.JTextArea entrada1;
    private javax.swing.JComboBox<String> filtroTablaGlobal;
    private javax.swing.JComboBox<String> filtroTablaGlobal1;
    private javax.swing.JComboBox<String> filtroTablaGlobal2;
    private javax.swing.JComboBox<String> filtroTablaGlobal3;
    private javax.swing.JComboBox<String> filtroTablaGlobal4;
    private javax.swing.JComboBox<String> filtroTablaGlobal5;
    private javax.swing.JComboBox<String> filtroTablaGlobal6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane10;
    private javax.swing.JDesktopPane jDesktopPane12;
    private javax.swing.JDesktopPane jDesktopPane13;
    private javax.swing.JDesktopPane jDesktopPane14;
    private javax.swing.JDesktopPane jDesktopPane15;
    private javax.swing.JDesktopPane jDesktopPane16;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable parametrosFunciones;
    private javax.swing.JTextArea salida;
    private javax.swing.JTable tablaCantidadFOM;
    private javax.swing.JTable tablaDeEL;
    private javax.swing.JTable tablaDeES;
    public static javax.swing.JTable tablaEstados;
    private javax.swing.JTable tablaSimbolos;
    // End of variables declaration//GEN-END:variables
}
